$('#questionAskedByYou').click(function(){
	$('#questionAskedByYou').addClass("active");
	$('#questions').removeClass("active");
	$('#answerdByYou').removeClass("active");
});
$('#questions').click(function(){
	$('#questions').addClass("active");
	$('#questionAskedByYou').removeClass("active");
	$('#answerdByYou').removeClass("active");
});
$('#answerdByYou').click(function(){
	$('#answerdByYou').addClass("active");
	$('#questions').removeClass("active");
	$('#questionAskedByYou').removeClass("active");
});